### ISSUE TITLE
Some confusion about selected by pseudo_labels

### ISSUE THREAD

**Issue by CSer-Tang-hao** [Lecanyu/ContinualLocalReplacement#1]
Hi, @Lecanyu 
I think this is an interesting and inspiring work, but in your released code, I found that you set "high_confidence=False" in your default setting. When I set it to True, I found that the accuracy was much worse. "high_confidence=True" is supposed to produce better results, but the opposite is true. I did not find a reasonable explanation about this issue in your paper. Looking forward to your reply!

**Comment by Lecanyu** [comment]
Hi, 

Yes, "high_confidence=False" produces worse results in experiments. This is a little bit counter-intuitive but still reasonable. 

The reason might be two folds:
1. "high_confidence" may not be a true semantically similar image, especially on the beginning of fine tune epoch. If we force it, wrong images are likely selected and wrong semantic information will be reinforced during the learning.
2. If we set "high_confidence=True", it is liable to select a fixed small subset from all unlabeled image. Such subset could be biased and lack information diversity.

**Comment by CSer-Tang-hao** [comment]
> Hi,
> 
> Yes, "high_confidence=False" produces worse results in experiments. This is a little bit counter-intuitive but still reasonable.
> 
> The reason might be two folds:
> 
> 1. "high_confidence" may not be a true semantically similar image, especially on the beginning of fine tune epoch. If we force it, wrong images are likely selected and wrong semantic information will be reinforced during the learning.
> 2. If we set "high_confidence=True", it is liable to select a fixed small subset from all unlabeled image. Such subset could be biased and lack information diversity.

Hi, @Lecanyu. Thanks for your quick reply. I notice that you normalize classifier weight after classifier forward, but I find that in many other codes, they usually use cos classifier by normalizing classifier weight and feature before classifier forward. Can you explain the difference? Whether it can make a difference in performance?

**Comment by Lecanyu** [comment]
Hi, 

I just checked the codes. 

If I understand you correctly, on training stage, the classifier weights are normalized before forward propagation except the first iteration. But it should have negligible effect on performance. On fine tune stage, the classifier weights are always normalized before forward propagation.

**Comment by CSer-Tang-hao** [comment]
> Hi,
> 
> I just checked the codes.
> 
> If I understand you correctly, on training stage, the classifier weights are normalized before forward propagation except the first iteration. But it should have negligible effect on performance. On fine tune stage, the classifier weights are always normalized before forward propagation.

Thanks! I find that the classifier weights are always normalized after forwarding propagation in your codes whether on training stage or fine-tune stage. I also notice that your code template is modified from [CloserLookFewShot](https://github.com/wyharveychen/CloserLookFewShot), I'm just comparing your code to it's "Baseline++". So I have the confusion as shown above.
